import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Boshlang'ich mahsulotlar — K-Beauty Store Optom ombori.
 * Faqat bitta narx ma'lum bo'lgan mahsulotlarda dona = optom qilib qo'yilgan,
 * ularni Admin Panelda istalgan vaqtda tuzatish mumkin.
 */
const PRODUCTS = [
  {
    name: 'ANUA Heartleaf Penka (Cleansing Foam)',
    nameRu: 'ANUA Heartleaf Пенка для умывания',
    brand: 'ANUA',
    category: 'tozalovchi',
    volume: '150 ml',
    imageUrl: '/uploads/anua-cleansing-foam.webp',
    pricePiece: 8000,
    priceWholesale: 7000,
    minWholesaleQty: 10,
    expiryDate: new Date('2027-05-24'),
    inStock: true,
    stockQty: 0,
    sortOrder: 1,
    description: [
      '• Succinic Acid 0.5% — teridagi yog‘ni muvozanatlaydi',
      '• Houttuynia Cordata ekstrakti 10 000 ppm — tinchlantiruvchi ta’sir',
      '• Terini quritmaydi, namlikni saqlaydi',
      '• Har kuni ertalab va kechqurun ishlatish mumkin',
      '• Sezgir teri uchun ham mos',
    ].join('\n'),
    descriptionRu: [
      '• Янтарная кислота 0.5% — контроль жирности кожи',
      '• Экстракт хауттюйнии 10 000 ppm — успокаивающий эффект',
      '• Не сушит кожу, сохраняет увлажнённость',
      '• Подходит для применения утром и вечером',
      '• Подходит для чувствительной кожи',
    ].join('\n'),
  },
  {
    name: 'ANUA Heartleaf 77 Clear Pad (70 dona)',
    nameRu: 'ANUA Heartleaf 77 Clear Pad (70 шт)',
    brand: 'ANUA',
    category: 'tozalovchi',
    volume: '70 pads / 205 ml',
    imageUrl: '/uploads/anua-77-clear-pad.webp',
    pricePiece: 7000,
    priceWholesale: 7000,
    minWholesaleQty: 10,
    expiryDate: new Date('2027-06-13'),
    inStock: true,
    stockQty: 0,
    sortOrder: 2,
    description: [
      '• Heartleaf 77% + PHA — yumshoq pilling',
      '• O‘lik hujayralarni va qora nuqtalarni tozalaydi',
      '• Teri teksturasini silliqlaydi',
      '• Bir karobkada 40 ta dona (optom uchun)',
      '• Srogi: 13.06.2027',
    ].join('\n'),
    descriptionRu: [
      '• Heartleaf 77% + PHA — мягкий пилинг',
      '• Очищает поры и убирает чёрные точки',
      '• Выравнивает текстуру кожи',
      '• В коробке 40 шт (для опта)',
      '• Срок годности: 13.06.2027',
    ].join('\n'),
  },
  {
    name: 'Oqartiruvchi Krem (White Secret Tone-up Cream)',
    nameRu: 'Отбеливающий крем (White Secret Tone-up Cream)',
    brand: 'AITEKI',
    category: 'krem',
    volume: '50 g',
    imageUrl: '/uploads/whitening-cream.png',
    pricePiece: 9000,
    priceWholesale: 8500,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 3,
    description: [
      '• Yuz va tanani oqartiruvchi tone-up krem',
      '• Qo‘ltiq osti, tizza va tirsak uchun ham mos',
      '• Teri rangini tekislaydi',
      '• Namlantiradi va yumshatadi',
      '• Kunlik parvarish uchun',
    ].join('\n'),
    descriptionRu: [
      '• Осветляющий тон-ап крем для лица и тела',
      '• Подходит для подмышек, коленей и локтей',
      '• Выравнивает тон кожи',
      '• Увлажняет и смягчает',
      '• Для ежедневного ухода',
    ].join('\n'),
  },
  {
    name: 'MEDIPEEL Peptide 9 Volume Bio Tox Pro',
    nameRu: 'MEDIPEEL Peptide 9 Volume Bio Tox Pro',
    brand: 'MEDIPEEL',
    category: 'serum',
    volume: '50 ml',
    imageUrl: null,
    pricePiece: 32500,
    priceWholesale: 32500,
    minWholesaleQty: 5,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 4,
    description: [
      '• Ajinlar va qarish belgilariga qarshi intensiv parvarish',
      '• Peptidlar + gidrolizlangan kollagen',
      '• Ectoin va Hyaluronic Acid kompleksi',
      '• Teri tarangligi, elastikligi va hajmini qo‘llab-quvvatlaydi',
      '• Qarishga qarshi kompleks parvarish',
    ].join('\n'),
    descriptionRu: [
      '• Интенсивный уход против морщин и старения',
      '• Пептиды + гидролизованный коллаген',
      '• Комплекс Ectoin и гиалуроновой кислоты',
      '• Поддерживает упругость, эластичность и объём кожи',
      '• Комплексный антивозрастной уход',
    ].join('\n'),
  },

  // ===== ANUA PDRN liniyasi =====
  {
    name: 'ANUA PDRN Hyaluron Cleanser',
    nameRu: 'ANUA PDRN Hyaluron Очищающее средство',
    brand: 'ANUA',
    category: 'tozalovchi',
    volume: '150 ml',
    imageUrl: '/uploads/anua-pdrn-line.webp',
    pricePiece: 9500,
    priceWholesale: 9500,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 5,
    description: [
      '• PDRN + Hyaluronic Acid kompleksi',
      '• Chuqur tozalaydi, terini tortishtirmaydi',
      '• Namlikni ushlab turadi',
      '• PDRN liniyasining 1-bosqichi',
    ].join('\n'),
    descriptionRu: [
      '• Комплекс PDRN + гиалуроновая кислота',
      '• Глубоко очищает, не стягивает кожу',
      '• Удерживает влагу',
      '• Первый шаг линии PDRN',
    ].join('\n'),
  },
  {
    name: 'ANUA PDRN Hyaluron Toner',
    nameRu: 'ANUA PDRN Hyaluron Тонер',
    brand: 'ANUA',
    category: 'toner',
    volume: '250 ml',
    imageUrl: '/uploads/anua-pdrn-line.webp',
    pricePiece: 15000,
    priceWholesale: 15000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 6,
    description: [
      '• PDRN + Hyaluron — chuqur namlantirish',
      '• Teri pH balansini tiklaydi',
      '• Keyingi vositalar so‘rilishini oshiradi',
      '• PDRN liniyasining 2-bosqichi',
    ].join('\n'),
    descriptionRu: [
      '• PDRN + гиалурон — глубокое увлажнение',
      '• Восстанавливает pH баланс кожи',
      '• Улучшает впитывание следующих средств',
      '• Второй шаг линии PDRN',
    ].join('\n'),
  },
  {
    name: 'ANUA PDRN Hyaluron Serum',
    nameRu: 'ANUA PDRN Hyaluron Сыворотка',
    brand: 'ANUA',
    category: 'serum',
    volume: '30 ml',
    imageUrl: '/uploads/anua-pdrn-line.webp',
    pricePiece: 21000,
    priceWholesale: 21000,
    minWholesaleQty: 5,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 7,
    description: [
      '• Yuqori konsentratsiyali PDRN ampula',
      '• Teri yangilanishini tezlashtiradi',
      '• Yorqinlik va namlik beradi',
      '• PDRN liniyasining 3-bosqichi',
    ].join('\n'),
    descriptionRu: [
      '• Высококонцентрированная ампула PDRN',
      '• Ускоряет обновление кожи',
      '• Придаёт сияние и увлажнение',
      '• Третий шаг линии PDRN',
    ].join('\n'),
  },
  {
    name: 'ANUA PDRN Hyaluron Krem',
    nameRu: 'ANUA PDRN Hyaluron Крем',
    brand: 'ANUA',
    category: 'krem',
    volume: '50 ml',
    imageUrl: '/uploads/anua-pdrn-line.webp',
    pricePiece: 16000,
    priceWholesale: 16000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 8,
    description: [
      '• Yengil, yopishmaydigan tekstura',
      '• Namlikni kun bo‘yi ushlab turadi',
      '• Teri to‘sig‘ini mustahkamlaydi',
      '• PDRN liniyasining yakuniy bosqichi',
    ].join('\n'),
    descriptionRu: [
      '• Лёгкая, нелипкая текстура',
      '• Удерживает влагу в течение дня',
      '• Укрепляет барьер кожи',
      '• Финальный шаг линии PDRN',
    ].join('\n'),
  },
  {
    name: 'ANUA PDRN Glow Pad',
    nameRu: 'ANUA PDRN Glow Pad',
    brand: 'ANUA',
    category: 'tozalovchi',
    volume: '80 ml / 30 pads',
    imageUrl: '/uploads/anua-pdrn-line.webp',
    pricePiece: 14000,
    priceWholesale: 14000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 9,
    description: [
      '• PDRN shimdirilgan yorqinlik padlari',
      '• Teriga bir zumda namlik beradi',
      '• Yo‘lda ham qulay ishlatiladi',
      '• Haftasiga 3-4 marta',
    ].join('\n'),
    descriptionRu: [
      '• Пады с PDRN для сияния',
      '• Мгновенно увлажняют кожу',
      '• Удобны в дороге',
      '• 3-4 раза в неделю',
    ].join('\n'),
  },
  {
    name: 'ANUA PDRN Capsule Mist 1+1 (100ml x2)',
    nameRu: 'ANUA PDRN Capsule Mist 1+1 (100ml x2)',
    brand: 'ANUA',
    category: 'toner',
    volume: '100 ml + 100 ml',
    imageUrl: '/uploads/anua-pdrn-mist.webp',
    pricePiece: 32000,
    priceWholesale: 32000,
    minWholesaleQty: 5,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 10,
    description: [
      '• 1+1 to‘plam — ikkita flakon',
      '• PDRN + Hyaluronic Acid kapsulalari',
      '• Kun davomida namlik va yorqinlik',
      '• Makiyaj ustidan ham purkash mumkin',
    ].join('\n'),
    descriptionRu: [
      '• Набор 1+1 — два флакона',
      '• Капсулы PDRN + гиалуроновая кислота',
      '• Увлажнение и сияние в течение дня',
      '• Можно распылять поверх макияжа',
    ].join('\n'),
  },
  {
    name: 'AXIS-Y Glass Skin Duo (2 ta to‘plam)',
    nameRu: 'AXIS-Y Glass Skin Duo (набор из 2)',
    brand: 'AXIS-Y',
    category: 'serum',
    volume: 'Serum + Eye serum',
    imageUrl: '/uploads/axis-y-glass-skin-duo.webp',
    pricePiece: 16000,
    priceWholesale: 16000,
    minWholesaleQty: 5,
    expiryDate: null,
    inStock: true,
    stockQty: 12,
    sortOrder: 11,
    description: [
      '• Dark Spot Correcting Glow Serum — 5% Niacinamide',
      '• Vegan Collagen Eye Serum — ko‘z atrofi uchun',
      '• Qora dog‘lar va xira terini yorqinlashtiradi',
      '• ⚠️ Soni kam — tezroq buyurtma bering',
    ].join('\n'),
    descriptionRu: [
      '• Dark Spot Correcting Glow Serum — 5% ниацинамид',
      '• Vegan Collagen Eye Serum — для области глаз',
      '• Осветляет пигментацию и тусклую кожу',
      '• ⚠️ Количество ограничено — успейте заказать',
    ].join('\n'),
  },

  // ===== LACTOFIT =====
  {
    name: 'LACTOFIT Gold (골드)',
    nameRu: 'LACTOFIT Gold (пробиотики)',
    brand: 'LACTOFIT',
    category: 'bad',
    volume: '2 g x 60 paket',
    imageUrl: '/uploads/lactofit.webp',
    pricePiece: 9000,
    priceWholesale: 9000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 12,
    description: [
      '• Koreyada №1 probiotik brend',
      '• 40 mlrd CFU foydali bakteriya',
      '• Ovqat hazm qilishni yaxshilaydi',
      '• Rux (Zinc) bilan boyitilgan',
      '• Kuniga 1 paket',
    ].join('\n'),
    descriptionRu: [
      '• Пробиотик №1 в Корее',
      '• 40 млрд КОЕ полезных бактерий',
      '• Улучшает пищеварение',
      '• Обогащён цинком',
      '• 1 саше в день',
    ].join('\n'),
  },
  {
    name: 'LACTOFIT Slim (슬림)',
    nameRu: 'LACTOFIT Slim (для стройности)',
    brand: 'LACTOFIT',
    category: 'bad',
    volume: '2 g x 60 paket',
    imageUrl: '/uploads/lactofit.webp',
    pricePiece: 15000,
    priceWholesale: 15000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 13,
    description: [
      '• Vazn nazorati uchun probiotik',
      '• Garciniya Kambodja ekstrakti bilan',
      '• Probiotiklar miqdori 2 barobar ko‘p',
      '• Kuniga 1 paket',
    ].join('\n'),
    descriptionRu: [
      '• Пробиотик для контроля веса',
      '• С экстрактом гарцинии камбоджийской',
      '• В 2 раза больше пробиотиков',
      '• 1 саше в день',
    ].join('\n'),
  },
  {
    name: 'LACTOFIT Diet (다이어트)',
    nameRu: 'LACTOFIT Diet (диета)',
    brand: 'LACTOFIT',
    category: 'bad',
    volume: '2 g x 60 paket',
    imageUrl: '/uploads/lactofit.webp',
    pricePiece: 15000,
    priceWholesale: 15000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 14,
    description: [
      '• Parhez davrida ichak mikroflorasini qo‘llab-quvvatlaydi',
      '• Garciniya + aminokislotalar',
      '• Ortiqcha vazndan xalos bo‘lishga yordam beradi',
      '• Kuniga 1 paket',
    ].join('\n'),
    descriptionRu: [
      '• Поддерживает микрофлору во время диеты',
      '• Гарциния + аминокислоты',
      '• Помогает в снижении веса',
      '• 1 саше в день',
    ].join('\n'),
  },
  {
    name: 'LACTOFIT 당케어 (Shakar uchun)',
    nameRu: 'LACTOFIT 당케어 (контроль сахара)',
    brand: 'LACTOFIT',
    category: 'bad',
    volume: '2 g x 60 paket',
    imageUrl: '/uploads/lactofit.webp',
    pricePiece: 12000,
    priceWholesale: 12000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 15,
    description: [
      '• Qondagi shakar darajasini qo‘llab-quvvatlaydi',
      '• Banaba bargi ekstrakti + rux',
      '• Probiotiklar bilan birga',
      '• Kuniga 1 paket',
    ].join('\n'),
    descriptionRu: [
      '• Поддерживает уровень сахара в крови',
      '• Экстракт листьев банабы + цинк',
      '• В комплексе с пробиотиками',
      '• 1 саше в день',
    ].join('\n'),
  },
  {
    name: 'LACTOFIT 간케어 (Jigar uchun)',
    nameRu: 'LACTOFIT 간케어 (для печени)',
    brand: 'LACTOFIT',
    category: 'bad',
    volume: '2 g x 60 paket',
    imageUrl: '/uploads/lactofit.webp',
    pricePiece: 12000,
    priceWholesale: 12000,
    minWholesaleQty: 10,
    expiryDate: null,
    inStock: true,
    stockQty: 0,
    sortOrder: 16,
    description: [
      '• Jigar funksiyasini qo‘llab-quvvatlaydi',
      '• Tikanli qoqio‘t (milk thistle) ekstrakti',
      '• Vitamin B kompleksi',
      '• Kuniga 1 paket',
    ].join('\n'),
    descriptionRu: [
      '• Поддерживает функцию печени',
      '• Экстракт расторопши (milk thistle)',
      '• Комплекс витаминов группы B',
      '• 1 саше в день',
    ].join('\n'),
  },
];

async function main() {
  const reset = process.argv.includes('--reset');
  const count = await prisma.product.count();

  if (count > 0 && !reset) {
    console.log(`ℹ️  Bazada allaqachon ${count} ta mahsulot bor. Seed o'tkazib yuborildi.`);
    console.log("   Hammasini o'chirib qaytadan yozish uchun: npm run db:seed -- --reset");
    return;
  }

  if (reset) {
    await prisma.product.deleteMany();
    console.log("🧹 Eski mahsulotlar o'chirildi.");
  }

  await prisma.product.createMany({ data: PRODUCTS });
  console.log(`✅ ${PRODUCTS.length} ta mahsulot bazaga yozildi.`);
}

main()
  .catch((e) => {
    console.error('❌ Seed xatosi:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
